name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Create Missing Android Project Files
        run: flutter create . --platforms android --project-name kc_kinjal

      - name: Install dependencies
        run: flutter pub get

      - name: Generate App Icons
        run: |
          flutter pub run flutter_launcher_icons:main || true

      - name: Build APK
        run: flutter build apk --release --dart-define=GEMINI_KEY="${{ secrets.GEMINI_KEY }}"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
